/** Create a portable, offline review worksheet; no external assets or requests. */
import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { createHash } from 'node:crypto'

const directory = path.dirname(fileURLToPath(import.meta.url))
const input = process.argv[2]
const output = process.argv[3]
if (!input || !output) throw new Error('Usage: node evaluations/build-review.mjs results.json output.html')
const fixture = JSON.parse(await fs.readFile(path.join(directory, 'cases.json'), 'utf8'))
const reportText = await fs.readFile(input, 'utf8')
const report = JSON.parse(reportText)
const comparison = process.argv[4] ? JSON.parse(await fs.readFile(process.argv[4], 'utf8')) : null
let review = null
try {
  const candidate = JSON.parse(await fs.readFile(path.join(directory, 'results/exploratory-review.json'), 'utf8'))
  if (candidate.inputSha256 === createHash('sha256').update(reportText).digest('hex')) review = candidate
} catch { /* The worksheet also supports fresh, unreviewed runs. */ }
const payload = JSON.stringify({ fixture, report, comparison, review }).replace(/</g, '\\u003c').replace(/\u2028/g, '\\u2028').replace(/\u2029/g, '\\u2029')
const html = `<!doctype html>
<html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Kit AI · Model review</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#fff9fb;color:#29222a;font:16px/1.6 system-ui,sans-serif}main{max-width:1180px;margin:auto;padding:32px 20px 80px}header{padding:12px 0 24px;border-bottom:1px solid #e9dce3}h1{font-size:clamp(26px,5vw,40px);line-height:1.15;margin:6px 0 18px;letter-spacing:-.04em}h2{font-size:23px;margin:0}h3{font-size:14px;text-transform:uppercase;letter-spacing:.08em;color:#745d6a;margin:0 0 12px}p{margin:10px 0}.brand{font-weight:750;color:#c43477;letter-spacing:.03em}.lede{max-width:800px}.notice{padding:14px 18px;border-left:3px solid #c43477;background:#f6eaf0;border-radius:0 10px 10px 0;margin:24px 0}.toolbar{display:flex;flex-wrap:wrap;align-items:center;gap:12px;margin:24px 0}button{font:inherit;border:1px solid #cfb8c4;border-radius:10px;padding:10px 16px;background:white;color:#442739;cursor:pointer;min-height:44px}button.primary{background:#a82765;color:white;border-color:#a82765}button:focus-visible,select:focus-visible,textarea:focus-visible,summary:focus-visible{outline:3px solid #c43477;outline-offset:3px}.meta{color:#6e6067;font-size:14px;overflow-wrap:anywhere}.pair{margin:32px 0 48px;scroll-margin-top:20px}.pair-title{display:flex;align-items:baseline;gap:12px;flex-wrap:wrap;margin-bottom:15px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}.card{padding:22px;background:white;border:1px solid #e8dce2;border-radius:16px;min-width:0}.question{font-weight:650;min-height:72px}.answer{white-space:pre-wrap;overflow-wrap:anywhere;border-top:1px solid #eee2e8;border-bottom:1px solid #eee2e8;padding:18px 0;margin:18px 0;font-size:15px}.status{font-size:13px;color:#745d6a}.missing{color:#934438}.controls{display:grid;gap:8px}label{font-size:14px;font-weight:600}select,textarea{font:inherit;width:100%;border:1px solid #d4c0cb;border-radius:8px;padding:10px;background:white;color:inherit}textarea{resize:vertical;min-height:80px}details{margin-top:20px}summary{cursor:pointer;padding:8px 0;font-weight:600}li{margin:6px 0}a{color:#9d225d;overflow-wrap:anywhere}.progress{margin-left:auto;color:#6e6067}footer{border-top:1px solid #e9dce3;padding-top:20px}.tags{display:flex;gap:8px;flex-wrap:wrap}.tag{font-size:12px;border-radius:99px;background:#f8edf2;padding:3px 10px}@media(max-width:700px){.grid{grid-template-columns:1fr}.question{min-height:0}.card{padding:18px}main{padding:24px 14px 60px}.progress{width:100%;margin-left:0}}@media print{button,.toolbar{display:none}.pair{break-inside:avoid}body{background:white}}
</style><main><header><div class="brand">kit + ai / learning lab</div><h1>Your model, under the microscope.</h1><p class="lede">Read the English and Spanish answers side by side. Mark confusing wording, missing steps, or anything you want us to investigate. These examples are for evaluation and are kept separate from training.</p><p class="meta" id="run"></p></header>
<div class="notice"><strong>Experimental answers, awaiting medical review.</strong> A generated answer is evidence that the model ran; it is not a passing accuracy score. Source-based criteria below are a draft and still need qualified clinical and Spanish-language review.</div>
<div class="toolbar"><button class="primary" id="download">Download my review</button><button id="toggle">Show review criteria</button><span class="progress" id="progress"></span></div><p class="meta">Your notes stay in this browser when storage is available. Download your review to keep a copy. This page makes no network requests.</p><div id="cases"></div>
<footer><strong>The first AI engineering lesson</strong><p>Evaluation measures behavior on examples. A prompt changes the instructions; retrieval adds source material; fine-tuning changes the model’s learned weights. A conversion changes how those weights are stored and executed. We compare answers before and after each change.</p><p class="meta" id="timing"></p></footer></main>
<script type="application/json" id="data">${payload}</script>
<script>
const {fixture,report,comparison,review}=JSON.parse(document.querySelector('#data').textContent);
const key='kit-evaluation-review:'+report.datasetSha256+':'+report.startedAt;let reviews={};try{reviews=JSON.parse(localStorage.getItem(key)||'{}')}catch{}
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n};
const update=()=>{document.querySelector('#progress').textContent=Object.values(reviews).filter(r=>r.clarity||r.notes).length+' / '+fixture.cases.length+' answers annotated';try{localStorage.setItem(key,JSON.stringify(reviews))}catch{}};
document.querySelector('#run').textContent=report.model+' · '+(report.stage||'Hosted model')+' · '+report.startedAt.slice(0,10)+' · '+report.generated+'/'+report.selectedCaseIds.length+' answers generated · '+(report.mode==='app'?'Kit reference-grounded prompt':'Bare question prompt');
document.querySelector('#timing').textContent=report.timingDescription;
const pairs=new Map();for(const c of fixture.cases){if(!pairs.has(c.pairId))pairs.set(c.pairId,[]);pairs.get(c.pairId).push(c)}
let count=0;for(const [pairId,cases]of pairs){const section=el('section',undefined,'pair');section.id=pairId;const title=el('div',undefined,'pair-title');title.append(el('h2',String(++count).padStart(2,'0')+' · '+cases[0].topic.replaceAll('-',' ')));const tag=el('span',cases[0].urgency,'tag');title.append(tag);section.append(title);const finding=review?.findings.find(f=>f.caseIds.some(id=>cases.some(c=>c.id===id)));if(finding){const note=el('div',undefined,'notice');note.append(el('strong','Exploratory review · '+finding.severity),el('p',finding.finding));section.append(note)}const grid=el('div',undefined,'grid');
for(const c of cases){const result=report.results.find(r=>r.caseId===c.id);const card=el('article',undefined,'card');card.lang=c.language;card.append(el('h3',c.language==='es'?'Español':'English'),el('p',c.prompt,'question'));
card.append(el('p',result?.status==='generated'?'Generated · '+(result.elapsedMs/1000).toFixed(1)+' seconds · accuracy unreviewed':result?.error||'Not run yet','status'));
card.append(el('div',result?.answer||'No model answer is available for this case.','answer'+(result?.answer?'':' missing')));
const later=comparison?.results.find(r=>r.caseId===c.id);if(later?.answer){const rerun=el('details');rerun.append(el('summary','Compare: after guide update'),el('p','Same model and question, updated guide matching/content. This is a known-case experiment, not an independent accuracy score.','meta'),el('div',later.answer,'answer'));card.append(rerun)}
const controls=el('div',undefined,'controls');const selectId=c.id+'-clarity';const label=el('label',c.language==='es'?'¿Se entiende con claridad?':'Is this easy to understand?');label.htmlFor=selectId;const select=el('select');select.id=selectId;for(const [value,text]of [['','Not reviewed'],['clear','Clear'],['unclear','Confusing'],['missing','Missing or concerning information']]){const o=el('option',text);o.value=value;select.append(o)}select.value=reviews[c.id]?.clarity||'';const notesId=c.id+'-notes';const notesLabel=el('label',c.language==='es'?'Notas para revisar juntos':'Notes to review together');notesLabel.htmlFor=notesId;const notes=el('textarea');notes.id=notesId;notes.value=reviews[c.id]?.notes||'';notes.placeholder=c.language==='es'?'¿Qué cambiarías o comprobarías?':'What would you change or check?';const save=()=>{reviews[c.id]={clarity:select.value,notes:notes.value,medicalAccuracy:'pending-qualified-review'};update()};select.addEventListener('change',save);notes.addEventListener('input',save);controls.append(label,select,notesLabel,notes);card.append(controls);
const detail=el('details');detail.append(el('summary','Source-based review criteria'));for(const [name,points]of [['Expected points',c.expectedPoints],['Critical omissions',c.criticalOmissions],['Dangerous claims to check',c.criticalDangerousClaims]]){if(!points?.length)continue;detail.append(el('strong',name));const list=el('ul');for(const point of points)list.append(el('li',point));detail.append(list)}const links=el('ul');for(const source of c.sources||[]){const li=el('li');const a=el('a',source.title);a.href=source.url;a.target='_blank';a.rel='noopener noreferrer';li.append(a);links.append(li)}detail.append(links);card.append(detail);grid.append(card)}section.append(grid);document.querySelector('#cases').append(section)}
document.querySelector('#download').addEventListener('click',()=>{const data={schemaVersion:1,reviewedAt:new Date().toISOString(),model:report.model,modelRevision:report.modelRevision,runStartedAt:report.startedAt,datasetSha256:report.datasetSha256,clinicalReview:'pending',reviews};const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=el('a');a.href=u;a.download='kit-ai-my-review.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),60000)});
document.querySelector('#toggle').addEventListener('click',e=>{const open=[...document.querySelectorAll('details')].some(d=>!d.open);document.querySelectorAll('details').forEach(d=>d.open=open);e.target.textContent=open?'Hide review criteria':'Show review criteria'});update();
</script></html>`
await fs.mkdir(path.dirname(path.resolve(output)), { recursive: true })
await fs.writeFile(output, html)
console.log(`Review worksheet: ${output}`)
