export const appCopy = {
  en: {
    audioUnavailable: 'Audio is unavailable on this phone. You can still read the answer.', ttsPlay: 'Listen', ttsPause: 'Pause', ttsGenerating: 'Preparing audio…', ttsError: 'Audio unavailable',
    guides: 'Guides', chat: 'Ask Kit', history: 'History', settings: 'Settings',
    newChat: 'New chat', newConversation: 'New conversation', mainNavigation: 'Main navigation', mobileNavigation: 'Mobile navigation',
    guidesSaved: 'Guides saved for offline', guidesIncluded: 'First-aid guides included', offline: 'Offline', companion: 'First-aid companion',
    shortDisclaimer: 'General information, not a diagnosis. In an emergency, call your local emergency number.',
    emergencyBanner: 'Immediate danger? Call your local emergency number. Don’t wait for Kit.',
    preparing: 'Preparing Kit for offline use…', downloading: 'Saving Kit for offline use… {progress}%', loadingSaved: 'Opening your saved assistant…',
    readyOffline: 'Kit can answer on this phone', readyDetail: 'Kit can answer while this page is open. To use it later without internet, the app must finish saving too.',
    savedReady: 'Saved for use without internet', savedReadyDetail: 'Kit and its answers are saved here. Try reopening without internet before you need it.', loadedOnlyDetail: 'Kit can answer while this page is open, but saving is not complete yet.',
    appSaving: 'Saving Kit to this phone…', appSaved: 'Kit is saved on this phone', appWaiting: 'Connect to finish saving Kit', appSaveFailed: 'Kit could not finish saving', appUnsupported: 'Saving is unavailable in this window', appRetry: 'Try saving again', appSaveDetail: 'Keep Kit open until saving finishes. Open it in the same browser when you return.',
    appGoogleWindowTitle: 'Open Kit in Safari or Chrome',
    appGoogleWindowDetail: 'This link is open in the Google app. This window cannot save Kit for use without internet. Copy the link, open Safari or Chrome itself, and paste it in the address bar.',
    appSeparateDownload: 'Downloads may not be shared between browsers. Use Wi-Fi if you choose to save answers again.',
    appUnsupportedDetail: 'Kit has not saved for use without internet. Waiting here will not finish saving. You can still use Kit while connected.',
    appSaveFailedDetail: 'Saving did not finish. Check your connection and try again. Your conversations will stay here.',
    appWaitingDetail: 'Connect to the internet, then try saving again in this browser.',
    appCheckAgain: 'Check again', appSavingHelp: 'Help with saving', appCheckBrowser: 'Check this browser',
    appOpenBrowserDetail: 'Copy this link and open it in a regular Safari or Chrome tab. If you are already using Chrome on an iPhone, try opening the same link in Safari.',
    appSecureDetail: 'Open the secure Kit link below in a new browser tab, then try saving again.',
    appHomeScreenDetail: 'On iPhone, you can also choose Share → Add to Home Screen. Open Kit from its new icon while connected and check whether saving finishes there.',
    appCopyLink: 'Copy Kit link', appLinkCopied: 'Link copied.', appLinkCopyFailed: 'Select and copy the link below.', appWebsite: 'Kit website',
    downloadConsentTitle: 'Want answers without internet?', downloadConsentDetail: 'Saving answers uses about 750 MB. Use Wi-Fi if you can. Kit and the first-aid guides save automatically without this large download.', downloadConsentAction: 'Save answers for offline use',
    checking: 'Checking offline support…', waitingConnection: 'Connect to finish offline setup', paused: 'Offline setup paused',
    limitedConnection: 'Download paused to save mobile data', limitedConnectionDetail: 'This download uses about 750 MB. Connect to Wi-Fi, or choose Download now to continue with your current connection.',
    unsupported: 'Answers need internet on this phone', unsupportedDetail: 'You can still read the guides here. Save Kit to read them later without internet.',
    setupFailed: 'Kit could not finish preparing answers', setupFailedDetail: 'Check your connection and free space, then try again. You can read the guides while you wait.',
    setupDetail: 'The first download for answers without internet uses about 750 MB. Keep Kit open until it finishes. You can pause to save data and keep reading the guides.',
    pause: 'Pause setup', resume: 'Resume setup', retry: 'Try setup again', downloadNow: 'Download now', downloadProgress: 'Offline setup progress',
    sourceDevice: 'Answering on your device', sourceOnline: 'Using online help', sourceGuides: 'Using saved guides',
    onlineNotice: 'With internet, your question is sent for an answer. Avoid names or other personal details. See Privacy in Settings.',
    deviceNotice: 'Questions answered on this device stay here. AI can make mistakes; check the linked guides.',
    guideNotice: 'Kit can show a matching first-aid guide while answers are unavailable.',
    welcomeTitle: 'What would you like to understand?', welcomeDetail: 'Ask a general health question, or start with a first-aid topic.',
    starterCut: 'How do I care for a small cut?', starterBurn: 'What should I do for a minor burn?',
    conversation: 'Conversation', thinking: 'Preparing your answer…', connecting: 'Preparing your answer…', waiting: 'Waiting for a response…',
    referenceMaterial: 'Reference material', previousConversation: 'Previous conversation', savedReference: 'Saved first-aid reference',
    answerUnavailable: 'Kit could not answer this time. Try again, or open a saved first-aid guide.', openGuides: 'Open first-aid guides', stopResponse: 'Stop response',
    inputPlaceholder: 'Ask a general health question…', sendMessage: 'Send message', characterCount: '{count} / 1,200 characters',
    historyTitle: 'Your conversations', historyDetail: 'Saved in this browser. Delete a conversation to remove it from this device.', noConversations: 'No conversations yet.', askQuestion: 'Ask Kit a question', deleteConversation: 'Delete {title}',
    settingsTitle: 'Settings', language: 'Language', languageDetail: 'Choose the language for Kit and your answers.',
    darkMode: 'Dark appearance', darkModeDesc: 'A softer screen in low light.', readAloud: 'Read answers aloud', readAloudDetail: 'Use the play button under an answer.', voiceSpeed: 'Voice speed',
    offlineSettings: 'Use without internet', storageDetail: 'Open Kit in the same browser each time. Your phone may remove saved files when space is low, or if you clear browsing data. Check Kit before you need it without internet.',
    autoSetup: 'Keep offline answers ready', autoSetupDetail: 'Open saved answers automatically when you return. You can turn this off and keep using the guides.',
    onlineHelp: 'Use internet for answers', onlineHelpDetail: 'When off, questions stay on this phone. Kit uses prepared answers or shows matching guides.',
    privacy: 'Privacy', privacyDetail: 'When internet answers are on, your question and recent messages from online conversations are sent to Hugging Face to prepare an answer. Avoid names, addresses, or other identifying details. When internet answers are off, questions stay on this device. Conversations are saved in this browser; deleting one removes it here.',
    takeWithYou: 'Take Kit with you', installDetail: 'On iPhone, open in Safari and choose Share → Add to Home Screen. On Android, use Install app or Add to Home Screen. Offline answers need a compatible device and completed setup.',
    aboutGuides: 'About these guides', aboutDetail: 'Six source-linked first-aid summaries in English and Spanish. Translations and AI answers have not had a clinical review. They cannot diagnose or replace professional care.',
    noGuide: 'No saved guide matches this question. Try a first-aid topic such as cuts, burns, or sprains. This library cannot assess symptoms.',
    guideAnswerIntro: 'Here is a matching first-aid guide. Kit cannot prepare an answer right now.',
    scope: 'Scope', whenToGetHelp: 'When to get help', sources: 'Sources',
  },
  es: {
    audioUnavailable: 'El audio no está disponible en este teléfono. Puedes leer la respuesta.', ttsPlay: 'Escuchar', ttsPause: 'Pausar', ttsGenerating: 'Preparando el audio…', ttsError: 'Audio no disponible',
    guides: 'Guías', chat: 'Pregunta a Kit', history: 'Historial', settings: 'Ajustes',
    newChat: 'Nuevo chat', newConversation: 'Nueva conversación', mainNavigation: 'Navegación principal', mobileNavigation: 'Navegación móvil',
    guidesSaved: 'Guías guardadas para usar sin conexión', guidesIncluded: 'Guías de primeros auxilios incluidas', offline: 'Sin conexión', companion: 'Tu ayuda de primeros auxilios',
    shortDisclaimer: 'Información general, no un diagnóstico. En una emergencia, llama al número de emergencias de tu zona.',
    emergencyBanner: '¿Hay peligro inmediato? Llama al número de emergencias de tu zona. No esperes a Kit.',
    preparing: 'Preparando Kit para usar sin conexión…', downloading: 'Guardando Kit para usar sin conexión… {progress}%', loadingSaved: 'Abriendo tu asistente guardado…',
    readyOffline: 'Kit puede responder en este teléfono', readyDetail: 'Kit puede responder mientras esta página esté abierta. Para usarlo después sin internet, la aplicación también debe terminar de guardarse.',
    savedReady: 'Guardado para usar sin internet', savedReadyDetail: 'Kit y sus respuestas están guardados aquí. Prueba a volver a abrirlo sin internet antes de necesitarlo.', loadedOnlyDetail: 'Kit puede responder mientras esta página esté abierta, pero todavía no ha terminado de guardarse.',
    appSaving: 'Guardando Kit en este teléfono…', appSaved: 'Kit está guardado en este teléfono', appWaiting: 'Conéctate para terminar de guardar Kit', appSaveFailed: 'Kit no pudo terminar de guardarse', appUnsupported: 'No se puede guardar Kit en esta ventana', appRetry: 'Volver a guardar', appSaveDetail: 'Mantén Kit abierto hasta que termine de guardarse. Usa el mismo navegador cuando vuelvas.',
    appGoogleWindowTitle: 'Abre Kit en Safari o Chrome',
    appGoogleWindowDetail: 'Este enlace está abierto en la aplicación de Google. Esta ventana no puede guardar Kit para usar sin internet. Copia el enlace, abre Safari o Chrome y pégalo en la barra de direcciones.',
    appSeparateDownload: 'Las descargas pueden no compartirse entre navegadores. Usa Wi-Fi si decides volver a guardar las respuestas.',
    appUnsupportedDetail: 'Kit no se ha guardado para usar sin internet. Esperar aquí no terminará de guardarlo. Puedes seguir usando Kit con conexión.',
    appSaveFailedDetail: 'No se terminó de guardar. Comprueba tu conexión y vuelve a intentarlo. Tus conversaciones seguirán aquí.',
    appWaitingDetail: 'Conéctate a internet y vuelve a intentar guardar Kit en este navegador.',
    appCheckAgain: 'Volver a comprobar', appSavingHelp: 'Ayuda para guardar Kit', appCheckBrowser: 'Comprobar este navegador',
    appOpenBrowserDetail: 'Copia este enlace y ábrelo en una pestaña normal de Safari o Chrome. Si ya usas Chrome en un iPhone, prueba el mismo enlace en Safari.',
    appSecureDetail: 'Abre el enlace seguro de Kit que aparece abajo en una pestaña nueva y vuelve a intentar guardarlo.',
    appHomeScreenDetail: 'En iPhone, también puedes elegir Compartir → Añadir a pantalla de inicio. Abre Kit desde el nuevo icono con conexión y comprueba si termina de guardarse allí.',
    appCopyLink: 'Copiar enlace de Kit', appLinkCopied: 'Enlace copiado.', appLinkCopyFailed: 'Selecciona y copia el enlace de abajo.', appWebsite: 'Sitio web de Kit',
    downloadConsentTitle: '¿Quieres respuestas sin internet?', downloadConsentDetail: 'Guardar las respuestas usa unos 750 MB. Usa Wi-Fi si puedes. Kit y las guías de primeros auxilios se guardan automáticamente sin esta descarga grande.', downloadConsentAction: 'Guardar respuestas para usar sin internet',
    checking: 'Comprobando si puedes usar Kit sin conexión…', waitingConnection: 'Conéctate para terminar la preparación', paused: 'Preparación sin conexión en pausa',
    limitedConnection: 'Descarga en pausa para ahorrar datos móviles', limitedConnectionDetail: 'Esta descarga usa unos 750 MB. Conéctate a Wi-Fi o elige Descargar ahora para continuar con tu conexión actual.',
    unsupported: 'Las respuestas necesitan internet en este teléfono', unsupportedDetail: 'Puedes seguir leyendo las guías aquí. Guarda Kit para consultarlas después sin internet.',
    setupFailed: 'Kit no pudo terminar de preparar las respuestas', setupFailedDetail: 'Comprueba tu conexión y el espacio libre, y vuelve a intentarlo. Puedes leer las guías mientras esperas.',
    setupDetail: 'La primera descarga para responder sin internet usa unos 750 MB. Mantén Kit abierto hasta que termine. Puedes pausar para ahorrar datos y seguir leyendo las guías.',
    pause: 'Pausar preparación', resume: 'Reanudar preparación', retry: 'Volver a intentar la preparación', downloadNow: 'Descargar ahora', downloadProgress: 'Progreso de la preparación sin conexión',
    sourceDevice: 'Respondiendo en tu dispositivo', sourceOnline: 'Usando ayuda en línea', sourceGuides: 'Usando las guías guardadas',
    onlineNotice: 'Con internet, tu pregunta se envía para obtener una respuesta. Evita nombres u otros datos personales. Consulta Privacidad en Ajustes.',
    deviceNotice: 'Las preguntas que se responden en este dispositivo se quedan aquí. La IA puede equivocarse; consulta las guías enlazadas.',
    guideNotice: 'Kit puede mostrar una guía de primeros auxilios relacionada mientras las respuestas no estén disponibles.',
    welcomeTitle: '¿Qué te gustaría entender?', welcomeDetail: 'Haz una pregunta general sobre salud o empieza por un tema de primeros auxilios.',
    starterCut: '¿Cómo cuido un corte pequeño?', starterBurn: '¿Qué debo hacer ante una quemadura leve?',
    conversation: 'Conversación', thinking: 'Preparando tu respuesta…', connecting: 'Preparando tu respuesta…', waiting: 'Esperando una respuesta…',
    referenceMaterial: 'Material de referencia', previousConversation: 'Conversación anterior', savedReference: 'Referencia de primeros auxilios guardada',
    answerUnavailable: 'Kit no pudo responder esta vez. Inténtalo de nuevo o abre una guía de primeros auxilios guardada.', openGuides: 'Abrir guías de primeros auxilios', stopResponse: 'Detener respuesta',
    inputPlaceholder: 'Haz una pregunta general sobre salud…', sendMessage: 'Enviar mensaje', characterCount: '{count} / 1.200 caracteres',
    historyTitle: 'Tus conversaciones', historyDetail: 'Guardadas en este navegador. Elimina una conversación para quitarla de este dispositivo.', noConversations: 'Aún no hay conversaciones.', askQuestion: 'Hazle una pregunta a Kit', deleteConversation: 'Eliminar {title}',
    settingsTitle: 'Ajustes', language: 'Idioma', languageDetail: 'Elige el idioma de Kit y de tus respuestas.',
    darkMode: 'Modo oscuro', darkModeDesc: 'Una pantalla más suave cuando hay poca luz.', readAloud: 'Leer respuestas en voz alta', readAloudDetail: 'Usa el botón de reproducción que aparece debajo de una respuesta.', voiceSpeed: 'Velocidad de la voz',
    offlineSettings: 'Usar sin internet', storageDetail: 'Abre Kit en el mismo navegador cada vez. Tu teléfono puede borrar lo guardado si queda poco espacio o si borras los datos de navegación. Comprueba Kit antes de necesitarlo sin internet.',
    autoSetup: 'Mantener listas las respuestas sin internet', autoSetupDetail: 'Abrir automáticamente las respuestas guardadas cuando vuelvas. Puedes desactivarlo y seguir usando las guías.',
    onlineHelp: 'Usar internet para responder', onlineHelpDetail: 'Si lo desactivas, las preguntas se quedan en este teléfono. Kit usa las respuestas preparadas o muestra guías relacionadas.',
    privacy: 'Privacidad', privacyDetail: 'Si activas las respuestas con internet, tu pregunta y los mensajes recientes de las conversaciones en línea se envían a Hugging Face para preparar una respuesta. Evita nombres, direcciones u otros datos que te identifiquen. Si desactivas las respuestas con internet, las preguntas se quedan en este dispositivo. Las conversaciones se guardan en este navegador; al borrar una, se elimina de aquí.',
    takeWithYou: 'Lleva Kit contigo', installDetail: 'En iPhone, abre Kit en Safari y elige Compartir → Añadir a pantalla de inicio. En Android, usa Instalar aplicación o Añadir a pantalla de inicio. Para obtener respuestas sin conexión necesitas un dispositivo compatible y haber completado la preparación.',
    aboutGuides: 'Acerca de estas guías', aboutDetail: 'Seis resúmenes de primeros auxilios en inglés y español, con enlaces a sus fuentes. Las traducciones y las respuestas de la IA no han pasado por una revisión clínica. No pueden diagnosticar ni sustituir la atención profesional.',
    noGuide: 'Ninguna guía guardada coincide con esta pregunta. Prueba con un tema de primeros auxilios, como cortes, quemaduras o esguinces. Esta biblioteca no puede evaluar síntomas.',
    guideAnswerIntro: 'Esta es una guía de primeros auxilios relacionada. Kit no puede preparar una respuesta en este momento.',
    scope: 'Alcance', whenToGetHelp: 'Cuándo buscar ayuda', sources: 'Fuentes',
  },
}
