export const appCopy = {
  en: {
    guides: 'Guides', chat: 'Ask Kit', history: 'History', settings: 'Settings',
    newChat: 'New chat', newConversation: 'New conversation', mainNavigation: 'Main navigation', mobileNavigation: 'Mobile navigation',
    guidesSaved: 'Guides saved for offline', guidesIncluded: 'First-aid guides included', offline: 'Offline', companion: 'First-aid companion',
    shortDisclaimer: 'General information, not a diagnosis. In an emergency, call your local emergency number.',
    emergencyBanner: 'Immediate danger? Call your local emergency number. Don’t wait for AI.',
    preparing: 'Preparing Kit for offline use…', downloading: 'Saving Kit for offline use… {progress}%', loadingSaved: 'Opening your saved assistant…',
    readyOffline: 'Ready to answer on this device', readyDetail: 'Kit’s assistant is loaded, and its files are saved in this browser for future visits.',
    checking: 'Checking offline support…', waitingConnection: 'Connect to finish offline setup', paused: 'Offline setup paused',
    limitedConnection: 'Waiting for Wi-Fi', limitedConnectionDetail: 'Data Saver or a cellular connection is enabled. You can resume the download now if you prefer.',
    unsupported: 'Saved guides are available on this device', unsupportedDetail: 'This browser cannot run the assistant on its graphics hardware. Kit can answer with online help when connected, and saved guides always remain available.',
    setupFailed: 'Offline setup could not finish', setupFailedDetail: 'Your browser may have run out of storage or memory, or the connection was interrupted. Saved guides are still available.',
    setupDetail: 'Kit automatically saves an assistant here (about 750 MB on the first visit). Keep this tab open until setup finishes. You can keep using Kit meanwhile.',
    pause: 'Pause setup', resume: 'Resume setup', retry: 'Try setup again', downloadNow: 'Download now', downloadProgress: 'Offline setup progress',
    sourceDevice: 'Answering on your device', sourceOnline: 'Using online help', sourceGuides: 'Using saved guides',
    onlineNotice: 'When connected, your question and recent online conversation go to Hugging Face for an answer from your medical assistant. Avoid identifying details. You can turn online help off in Settings.',
    deviceNotice: 'Questions answered on this device stay here. AI can make mistakes; check the linked guides.',
    guideNotice: 'Kit can find saved guidance while the assistant is unavailable. These are reference excerpts, not generated answers.',
    welcomeTitle: 'What would you like to understand?', welcomeDetail: 'Ask a general health question, or start with a first-aid topic.',
    starterCut: 'How do I care for a small cut?', starterBurn: 'What should I do for a minor burn?',
    conversation: 'Conversation', thinking: 'Thinking on this device…', connecting: 'Getting online help…', waiting: 'Waiting for a response…',
    referenceMaterial: 'Reference material', previousConversation: 'Previous conversation', savedReference: 'Saved first-aid reference',
    answerUnavailable: 'Kit could not answer this time. Try again, or open a saved first-aid guide.', openGuides: 'Open first-aid guides', stopResponse: 'Stop response',
    inputPlaceholder: 'Ask a general health question…', sendMessage: 'Send message', characterCount: '{count} / 1,200 characters',
    historyTitle: 'Your conversations', historyDetail: 'Saved in this browser. Delete a conversation to remove it from this device.', noConversations: 'No conversations yet.', askQuestion: 'Ask Kit a question', deleteConversation: 'Delete {title}',
    settingsTitle: 'Make yourself comfortable.', language: 'Language', languageDetail: 'Use Kit, search guides, and request answers in your preferred language.',
    darkMode: 'Dark appearance', darkModeDesc: 'A softer screen in low light.', readAloud: 'Read answers aloud', readAloudDetail: 'Use the play button under an answer.', voiceSpeed: 'Voice speed',
    offlineSettings: 'Offline access', storageDetail: 'Files stay in this browser unless you clear its data or the browser removes them to free space. Open Kit before a trip to check that it is ready.',
    autoSetup: 'Prepare automatically', autoSetupDetail: 'Save the assistant when connected and open it automatically on future visits.',
    onlineHelp: 'Online answers when connected', onlineHelpDetail: 'Use your medical assistant on Hugging Face when connected. When off, use the saved assistant or guides and keep questions on this device.',
    takeWithYou: 'Take Kit with you', installDetail: 'On iPhone, open in Safari and choose Share → Add to Home Screen. On Android, use Install app or Add to Home Screen. Offline answers need a compatible device and completed setup.',
    aboutGuides: 'About these guides', aboutDetail: 'Six source-linked first-aid summaries in English and Spanish. Translations and AI answers have not had a clinical review. They cannot diagnose or replace professional care.',
    viewProject: 'View the project', modelDetails: 'Assistant details', modelDetailText: 'Connected: your Llama 3.2 3B medical checkpoint. Offline: experimental Llama 3.2 1B. These are different models; your medical checkpoint still needs conversion for browsers. Both use matching saved guides. Kit does not search the web.',
    noGuide: 'No saved guide matches this question. Try a first-aid topic such as cuts, burns, or sprains. This library cannot assess symptoms.',
    guideAnswerIntro: 'Here is the matching saved guide. Kit is showing reference text because the assistant is unavailable.',
    scope: 'Scope', whenToGetHelp: 'When to get help', sources: 'Sources',
  },
  es: {
    guides: 'Guías', chat: 'Pregunta a Kit', history: 'Historial', settings: 'Ajustes',
    newChat: 'Nuevo chat', newConversation: 'Nueva conversación', mainNavigation: 'Navegación principal', mobileNavigation: 'Navegación móvil',
    guidesSaved: 'Guías guardadas para usar sin conexión', guidesIncluded: 'Guías de primeros auxilios incluidas', offline: 'Sin conexión', companion: 'Tu ayuda de primeros auxilios',
    shortDisclaimer: 'Información general, no un diagnóstico. En una emergencia, llama al número de emergencias de tu zona.',
    emergencyBanner: '¿Hay peligro inmediato? Llama al número de emergencias de tu zona. No esperes a la IA.',
    preparing: 'Preparando Kit para usar sin conexión…', downloading: 'Guardando Kit para usar sin conexión… {progress}%', loadingSaved: 'Abriendo tu asistente guardado…',
    readyOffline: 'Listo para responder en este dispositivo', readyDetail: 'El asistente de Kit está cargado y sus archivos están guardados en este navegador para futuras visitas.',
    checking: 'Comprobando si puedes usar Kit sin conexión…', waitingConnection: 'Conéctate para terminar la preparación', paused: 'Preparación sin conexión en pausa',
    limitedConnection: 'Esperando una conexión Wi-Fi', limitedConnectionDetail: 'El ahorro de datos está activado o estás usando datos móviles. Si lo prefieres, puedes reanudar la descarga ahora.',
    unsupported: 'Las guías guardadas están disponibles en este dispositivo', unsupportedDetail: 'Este navegador no puede ejecutar el asistente con el hardware gráfico de este dispositivo. Kit puede responder con ayuda en línea cuando hay conexión, y las guías guardadas siguen disponibles.',
    setupFailed: 'No se pudo completar la preparación sin conexión', setupFailedDetail: 'Es posible que el navegador se haya quedado sin espacio de almacenamiento o memoria, o que se haya interrumpido la conexión. Las guías guardadas siguen disponibles.',
    setupDetail: 'Kit guarda automáticamente un asistente aquí (unos 750 MB en la primera visita). Mantén esta pestaña abierta hasta que termine la preparación. Mientras tanto, puedes seguir usando Kit.',
    pause: 'Pausar preparación', resume: 'Reanudar preparación', retry: 'Volver a intentar la preparación', downloadNow: 'Descargar ahora', downloadProgress: 'Progreso de la preparación sin conexión',
    sourceDevice: 'Respondiendo en tu dispositivo', sourceOnline: 'Usando ayuda en línea', sourceGuides: 'Usando las guías guardadas',
    onlineNotice: 'Con conexión, tu pregunta y la conversación reciente en línea se envían a Hugging Face para que responda tu asistente médico. Evita incluir datos que te identifiquen. Puedes desactivar la ayuda en línea en Ajustes.',
    deviceNotice: 'Las preguntas que se responden en este dispositivo se quedan aquí. La IA puede equivocarse; consulta las guías enlazadas.',
    guideNotice: 'Kit puede buscar información guardada mientras el asistente no esté disponible. Estos son fragmentos de referencia, no respuestas generadas.',
    welcomeTitle: '¿Qué te gustaría entender?', welcomeDetail: 'Haz una pregunta general sobre salud o empieza por un tema de primeros auxilios.',
    starterCut: '¿Cómo cuido un corte pequeño?', starterBurn: '¿Qué debo hacer ante una quemadura leve?',
    conversation: 'Conversación', thinking: 'Pensando en este dispositivo…', connecting: 'Conectando con la ayuda en línea…', waiting: 'Esperando una respuesta…',
    referenceMaterial: 'Material de referencia', previousConversation: 'Conversación anterior', savedReference: 'Referencia de primeros auxilios guardada',
    answerUnavailable: 'Kit no pudo responder esta vez. Inténtalo de nuevo o abre una guía de primeros auxilios guardada.', openGuides: 'Abrir guías de primeros auxilios', stopResponse: 'Detener respuesta',
    inputPlaceholder: 'Haz una pregunta general sobre salud…', sendMessage: 'Enviar mensaje', characterCount: '{count} / 1.200 caracteres',
    historyTitle: 'Tus conversaciones', historyDetail: 'Guardadas en este navegador. Elimina una conversación para quitarla de este dispositivo.', noConversations: 'Aún no hay conversaciones.', askQuestion: 'Hazle una pregunta a Kit', deleteConversation: 'Eliminar {title}',
    settingsTitle: 'A tu gusto.', language: 'Idioma', languageDetail: 'Usa Kit, busca guías y solicita respuestas en tu idioma preferido.',
    darkMode: 'Modo oscuro', darkModeDesc: 'Una pantalla más suave cuando hay poca luz.', readAloud: 'Leer respuestas en voz alta', readAloudDetail: 'Usa el botón de reproducción que aparece debajo de una respuesta.', voiceSpeed: 'Velocidad de la voz',
    offlineSettings: 'Acceso sin conexión', storageDetail: 'Los archivos se quedan en este navegador hasta que borres sus datos o el navegador los elimine para liberar espacio. Abre Kit antes de un viaje para comprobar que está listo.',
    autoSetup: 'Preparar automáticamente', autoSetupDetail: 'Guardar el asistente cuando haya conexión y abrirlo automáticamente en futuras visitas.',
    onlineHelp: 'Respuestas en línea con conexión', onlineHelpDetail: 'Usar tu asistente médico de Hugging Face cuando haya conexión. Si desactivas esta opción, se usan el asistente guardado o las guías y las preguntas se quedan en este dispositivo.',
    takeWithYou: 'Lleva Kit contigo', installDetail: 'En iPhone, abre Kit en Safari y elige Compartir → Añadir a pantalla de inicio. En Android, usa Instalar aplicación o Añadir a pantalla de inicio. Para obtener respuestas sin conexión necesitas un dispositivo compatible y haber completado la preparación.',
    aboutGuides: 'Acerca de estas guías', aboutDetail: 'Seis resúmenes de primeros auxilios en inglés y español, con enlaces a sus fuentes. Las traducciones y las respuestas de la IA no han pasado por una revisión clínica. No pueden diagnosticar ni sustituir la atención profesional.',
    viewProject: 'Ver el proyecto', modelDetails: 'Detalles del asistente', modelDetailText: 'Con conexión: tu modelo médico Llama 3.2 3B. Sin conexión: Llama 3.2 1B experimental. Son modelos distintos; el modelo médico aún necesita conversión para el navegador. Ambos usan guías guardadas pertinentes. Kit no busca en Internet.',
    noGuide: 'Ninguna guía guardada coincide con esta pregunta. Prueba con un tema de primeros auxilios, como cortes, quemaduras o esguinces. Esta biblioteca no puede evaluar síntomas.',
    guideAnswerIntro: 'Esta es la guía guardada que coincide con tu pregunta. Kit muestra el texto de referencia porque el asistente no está disponible.',
    scope: 'Alcance', whenToGetHelp: 'Cuándo buscar ayuda', sources: 'Fuentes',
  },
}
