export const simpleChatCopy = {
  en: {
    menu: 'More options', back: 'Back to chat', history: 'Conversations', guides: 'First aid', settings: 'Settings',
    welcome: 'How can I help?', welcomeDetail: 'Ask Kit a health question.', placeholder: 'Ask a health question…',
    ready: 'Ready without internet', readyHere: 'Ready to answer', preparing: 'Getting ready…', internetNeeded: 'Internet needed', notReady: 'Not ready offline',
    setupLabel: 'Use Kit without internet', setupTitle: 'Take Kit offline',
    setupDetail: 'Download Kit once on Wi-Fi. Then ask questions without internet. Keep this page open until it finishes.',
    download: 'Download Kit · {size} GB', notNow: 'Ask with internet for now',
    downloadStarting: 'Starting the download…', downloadStarted: 'Downloading Kit… less than 1%', downloadProgress: 'Kit download progress',
    downloading: 'Downloading Kit… {progress}%', downloadDetail: 'Keep Kit open. This only needs to finish once in this browser.',
    loading: 'Opening Kit…', loadingDetail: 'Kit is preparing to answer on this phone. Keep this page open.',
    checking: 'Getting Kit ready…', checkingDetail: 'Getting everything ready. The download will show its progress once it starts.',
    saving: 'Saving Kit…', savingDetail: 'Saving the app so it can open without internet. Keep this page open.',
    preparingTakesTime: 'This step can take a few minutes. You can pause and return later.',
    openingTakesTime: 'Opening Kit can take a few minutes. You can pause if you need to leave this page.',
    interrupted: 'Kit had trouble staying open', interruptedDetail: 'Kit stopped unexpectedly. Any files already saved have been kept. It may need more memory than this phone can provide.',
    openFailed: 'Kit could not open', openFailedDetail: 'Any files already saved have been kept. Try opening Kit again. If it keeps closing, this phone may not have enough memory.',
    tryOpening: 'Try opening Kit', resumeOpening: 'Continue opening Kit',
    paused: 'Setup paused', pausedDetail: 'Your saved files are kept. Continue when you have time to keep Kit open.',
    waiting: 'Connect once to download Kit', waitingDetail: 'Kit is not fully downloaded here yet. Connect to Wi-Fi to finish, then you can ask questions without internet.',
    unsupported: 'This phone needs internet for Kit', unsupportedDetail: 'This version of Kit cannot run without internet on this phone. You can still ask questions when connected.',
    failed: 'The download did not finish', failedDetail: 'Check your connection and free space, then try again.',
    reopen: 'Kit needs to reopen', reopenDetail: 'Your question is saved. Try opening Kit again to continue.',
    saveIncomplete: 'Finish saving Kit', saveIncompleteDetail: 'Kit can answer now, but saving must finish before you can reopen it without internet.',
    retry: 'Try again', resume: 'Continue download', pause: 'Pause', openSettings: 'Get help',
    writing: 'Kit is thinking…', stop: 'Stop', stopped: 'Answer stopped.',
    answerFailed: 'Kit could not finish this answer. Your question is still here.', retryAnswer: 'Try this question again',
    noAnswer: 'Kit did not return an answer. Please try again.',
    offlineBlocked: 'Finish downloading Kit before asking without internet.',
    onlinePrivacy: 'Using internet for this answer. Avoid personal details.',
    disclaimer: 'Kit is experimental and can make mistakes. For urgent help, contact local emergency services.',
    sources: 'References', oldGuide: 'Saved first-aid note', historyEmpty: 'Your conversations will appear here.',
    noGuideAnswer: 'First-aid notes are available from the menu.',
  },
  es: {
    menu: 'Más opciones', back: 'Volver al chat', history: 'Conversaciones', guides: 'Primeros auxilios', settings: 'Ajustes',
    welcome: '¿Cómo puedo ayudarte?', welcomeDetail: 'Hazle una pregunta de salud a Kit.', placeholder: 'Haz una pregunta de salud…',
    ready: 'Listo sin internet', readyHere: 'Listo para responder', preparing: 'Preparando Kit…', internetNeeded: 'Necesita internet', notReady: 'Aún no está listo sin internet',
    setupLabel: 'Usar Kit sin internet', setupTitle: 'Lleva Kit sin conexión',
    setupDetail: 'Descarga Kit una vez con Wi-Fi. Después podrás hacer preguntas sin internet. Mantén esta página abierta hasta que termine.',
    download: 'Descargar Kit · {size} GB', notNow: 'Preguntar con internet por ahora',
    downloadStarting: 'Iniciando la descarga…', downloadStarted: 'Descargando Kit… menos del 1%', downloadProgress: 'Progreso de la descarga de Kit',
    downloading: 'Descargando Kit… {progress}%', downloadDetail: 'Mantén Kit abierto. Solo tiene que terminar una vez en este navegador.',
    loading: 'Abriendo Kit…', loadingDetail: 'Kit se está preparando para responder en este teléfono. Mantén esta página abierta.',
    checking: 'Preparando Kit…', checkingDetail: 'Preparando todo. Verás el progreso de la descarga cuando empiece.',
    saving: 'Guardando Kit…', savingDetail: 'Guardando la aplicación para abrirla sin internet. Mantén esta página abierta.',
    preparingTakesTime: 'Este paso puede tardar unos minutos. Puedes pausar y volver más tarde.',
    openingTakesTime: 'Abrir Kit puede tardar unos minutos. Puedes pausar si necesitas salir de esta página.',
    interrupted: 'Kit tuvo problemas para seguir abierto', interruptedDetail: 'Kit se detuvo inesperadamente. Se han conservado los archivos que ya se guardaron. Puede necesitar más memoria de la que tiene este teléfono.',
    openFailed: 'Kit no pudo abrirse', openFailedDetail: 'Se han conservado los archivos que ya se guardaron. Intenta abrir Kit de nuevo. Si sigue cerrándose, puede que este teléfono no tenga suficiente memoria.',
    tryOpening: 'Intentar abrir Kit', resumeOpening: 'Seguir abriendo Kit',
    paused: 'Preparación en pausa', pausedDetail: 'Tus archivos guardados se conservan. Continúa cuando tengas tiempo para mantener Kit abierto.',
    waiting: 'Conéctate una vez para descargar Kit', waitingDetail: 'Kit aún no se ha descargado por completo aquí. Conéctate a Wi-Fi para terminar y después podrás preguntar sin internet.',
    unsupported: 'Este teléfono necesita internet para usar Kit', unsupportedDetail: 'Esta versión de Kit no puede funcionar sin internet en este teléfono. Puedes preguntar cuando tengas conexión.',
    failed: 'La descarga no terminó', failedDetail: 'Comprueba la conexión y el espacio libre, y vuelve a intentarlo.',
    reopen: 'Hay que volver a abrir Kit', reopenDetail: 'Tu pregunta está guardada. Intenta abrir Kit de nuevo para continuar.',
    saveIncomplete: 'Termina de guardar Kit', saveIncompleteDetail: 'Kit puede responder ahora, pero debe terminar de guardarse para que puedas volver a abrirlo sin internet.',
    retry: 'Volver a intentar', resume: 'Continuar descarga', pause: 'Pausar', openSettings: 'Obtener ayuda',
    writing: 'Kit está pensando…', stop: 'Detener', stopped: 'Respuesta detenida.',
    answerFailed: 'Kit no pudo terminar la respuesta. Tu pregunta sigue aquí.', retryAnswer: 'Reintentar esta pregunta',
    noAnswer: 'Kit no dio una respuesta. Vuelve a intentarlo.',
    offlineBlocked: 'Termina de descargar Kit antes de preguntar sin internet.',
    onlinePrivacy: 'Esta respuesta usa internet. Evita los datos personales.',
    disclaimer: 'Kit es experimental y puede equivocarse. Si necesitas ayuda urgente, llama a los servicios de emergencia locales.',
    sources: 'Referencias', oldGuide: 'Nota de primeros auxilios guardada', historyEmpty: 'Tus conversaciones aparecerán aquí.',
    noGuideAnswer: 'Las notas de primeros auxilios están en el menú.',
  },
}
