export const simpleChatCopy = {
  en: {
    menu: 'More options', back: 'Back to chat', history: 'Conversations', guides: 'First aid', settings: 'Settings',
    welcome: 'How can I help?', welcomeDetail: 'Ask Kit a health question.', placeholder: 'Ask a health question…',
    ready: 'Ready without internet', readyHere: 'Ready to answer', preparing: 'Getting ready…', internetNeeded: 'Internet needed', notReady: 'Not ready offline',
    setupLabel: 'Use Kit without internet', setupTitle: 'Take Kit offline',
    setupDetail: 'Download Kit once on Wi-Fi. Then ask questions without internet. Keep this page open until it finishes.',
    download: 'Download Kit · {size} GB', notNow: 'Ask with internet for now',
    downloading: 'Downloading Kit… {progress}%', downloadDetail: 'Keep Kit open. This only needs to finish once in this browser.',
    loading: 'Opening Kit…', loadingDetail: 'Your saved assistant is getting ready to answer.',
    checking: 'Getting Kit ready…', checkingDetail: 'Checking whether this phone can save Kit.',
    saving: 'Saving Kit…', savingDetail: 'Keep this page open for a moment.',
    paused: 'Download paused', pausedDetail: 'Continue when you have Wi-Fi and time to keep Kit open.',
    waiting: 'Connect once to download Kit', waitingDetail: 'Kit is not fully downloaded here yet. Connect to Wi-Fi to finish, then you can ask questions without internet.',
    unsupported: 'This phone needs internet for Kit', unsupportedDetail: 'This version of Kit cannot run without internet on this phone. You can still ask questions when connected.',
    failed: 'The download did not finish', failedDetail: 'Check your connection and free space, then try again.',
    reopen: 'Kit needs to reopen', reopenDetail: 'Your question is saved. Try opening Kit again to continue.',
    saveIncomplete: 'Finish saving Kit', saveIncompleteDetail: 'Kit can answer now, but saving must finish before you can reopen it without internet.',
    retry: 'Try again', resume: 'Continue download', pause: 'Pause', openSettings: 'Get help',
    writing: 'Kit is thinking…', stop: 'Stop', stopped: 'Answer stopped.',
    answerFailed: 'Kit could not finish this answer. Your question is still here.', retryAnswer: 'Try this question again',
    noAnswer: 'Kit did not return an answer. Please try again.',
    offlineBlocked: 'Finish downloading Kit before asking without internet.',
    onlinePrivacy: 'Using internet for this answer. Avoid personal details.',
    disclaimer: 'Kit is experimental and can make mistakes. For urgent help, contact local emergency services.',
    sources: 'References', oldGuide: 'Saved first-aid note', historyEmpty: 'Your conversations will appear here.',
    noGuideAnswer: 'First-aid notes are available from the menu.',
  },
  es: {
    menu: 'Más opciones', back: 'Volver al chat', history: 'Conversaciones', guides: 'Primeros auxilios', settings: 'Ajustes',
    welcome: '¿Cómo puedo ayudarte?', welcomeDetail: 'Hazle una pregunta de salud a Kit.', placeholder: 'Haz una pregunta de salud…',
    ready: 'Listo sin internet', readyHere: 'Listo para responder', preparing: 'Preparando Kit…', internetNeeded: 'Necesita internet', notReady: 'Aún no está listo sin internet',
    setupLabel: 'Usar Kit sin internet', setupTitle: 'Lleva Kit sin conexión',
    setupDetail: 'Descarga Kit una vez con Wi-Fi. Después podrás hacer preguntas sin internet. Mantén esta página abierta hasta que termine.',
    download: 'Descargar Kit · {size} GB', notNow: 'Preguntar con internet por ahora',
    downloading: 'Descargando Kit… {progress}%', downloadDetail: 'Mantén Kit abierto. Solo tiene que terminar una vez en este navegador.',
    loading: 'Abriendo Kit…', loadingDetail: 'Tu asistente guardado se está preparando para responder.',
    checking: 'Preparando Kit…', checkingDetail: 'Comprobando si este teléfono puede guardar Kit.',
    saving: 'Guardando Kit…', savingDetail: 'Mantén esta página abierta un momento.',
    paused: 'Descarga en pausa', pausedDetail: 'Continúa cuando tengas Wi-Fi y tiempo para mantener Kit abierto.',
    waiting: 'Conéctate una vez para descargar Kit', waitingDetail: 'Kit aún no se ha descargado por completo aquí. Conéctate a Wi-Fi para terminar y después podrás preguntar sin internet.',
    unsupported: 'Este teléfono necesita internet para usar Kit', unsupportedDetail: 'Esta versión de Kit no puede funcionar sin internet en este teléfono. Puedes preguntar cuando tengas conexión.',
    failed: 'La descarga no terminó', failedDetail: 'Comprueba la conexión y el espacio libre, y vuelve a intentarlo.',
    reopen: 'Hay que volver a abrir Kit', reopenDetail: 'Tu pregunta está guardada. Intenta abrir Kit de nuevo para continuar.',
    saveIncomplete: 'Termina de guardar Kit', saveIncompleteDetail: 'Kit puede responder ahora, pero debe terminar de guardarse para que puedas volver a abrirlo sin internet.',
    retry: 'Volver a intentar', resume: 'Continuar descarga', pause: 'Pausar', openSettings: 'Obtener ayuda',
    writing: 'Kit está pensando…', stop: 'Detener', stopped: 'Respuesta detenida.',
    answerFailed: 'Kit no pudo terminar la respuesta. Tu pregunta sigue aquí.', retryAnswer: 'Reintentar esta pregunta',
    noAnswer: 'Kit no dio una respuesta. Vuelve a intentarlo.',
    offlineBlocked: 'Termina de descargar Kit antes de preguntar sin internet.',
    onlinePrivacy: 'Esta respuesta usa internet. Evita los datos personales.',
    disclaimer: 'Kit es experimental y puede equivocarse. Si necesitas ayuda urgente, llama a los servicios de emergencia locales.',
    sources: 'Referencias', oldGuide: 'Nota de primeros auxilios guardada', historyEmpty: 'Tus conversaciones aparecerán aquí.',
    noGuideAnswer: 'Las notas de primeros auxilios están en el menú.',
  },
}
